feat: creates 'Document' model
practice-uffs/web-feedback pull request #117
Opened 2020-09-12 23:23 UTC by JeanCHilger

closes #109

Esta PR cria o _model_ e a _migration_. Configurações adicionais referentes ao `storage` serão adicionados na resolução da issue #110.

2020-09-18 18:19 UTC, Dovyski requested changes
Ficou ótimo, só corrigir os detalhes que eu apontei.

2020-09-18 18:19 UTC, Dovyski commented on database/migrations/2020_09_12_225300_create_documents_table.php
> +            $table->string('path', 256);
Eu aumentaria esse número aqui para garantir que não teremos problemas. Um tamanho de `400` ou `512` não vai fazer mal a ninguém.

2020-09-18 18:19 UTC, Dovyski commented on database/migrations/2020_09_12_225300_create_documents_table.php
> +            $table->string('mime_type', 32);
Esse valor precisa ser [no mínimo 127](https://stackoverflow.com/questions/643690/maximum-mimetype-length-when-storing-type-in-db#:~:text=1%20Answer&text=According%20to%20RFC%204288%20%22Media,can%20be%20max%20127%20characters.) Vamos usar `128` e não teremos problemas.

2020-09-20 23:39 UTC, JeanCHilger commented
Os tamanhos foram alterados, o merge será efetuado em seguida.

2020-09-22 13:36 UTC, arufonsekun approved these changes
Tudo perfeito 👌, nada que eu possa apontar.

2020-09-22 23:17 UTC, merged